/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dong.hotel.login;

import dong.hotel.file.SFR100Process;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import dong.hotel.file.SFR100Process;
import dong.hotel.management.LoginDataInfo;
import dong.hotel.mainmenu.MainMenu; // 다음클래스호출 창넘김 용도 
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane; // 메세지 박스 띄우는 용도용 임포트 
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author heehe
 */
public class Login extends javax.swing.JFrame {

    ArrayList<LoginDataInfo> loginfo = new ArrayList<>();  // 객체 복사용도 
    Boolean alla;
    static int logintype = 0; // 0이면 관리자 , 1이면 스탭 
    
    public int getLogintypestate() {
        return logintype;
    }

    /**
     * Creates new form Logingui
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        F_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Login_BUTT = new javax.swing.JButton();
        F_PW = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("굴림", 1, 25)); // NOI18N
        jLabel1.setText("호텔 관리 시스템");

        jLabel2.setFont(new java.awt.Font("굴림", 0, 10)); // NOI18N
        jLabel2.setText("아이디");

        F_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_IDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("굴림", 0, 10)); // NOI18N
        jLabel3.setText("비밀번호");

        Login_BUTT.setText("로그인");
        Login_BUTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_BUTTActionPerformed(evt);
            }
        });

        jButton1.setText("이전");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(F_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(F_PW))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Login_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(F_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(F_PW, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Login_BUTT, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void F_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_IDActionPerformed

    private void Login_BUTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_BUTTActionPerformed
        /* 여기서부터 메인 코드 시작 */
        SFR100Process filea = new SFR100Process();  // sfr 100 클래스 객체 생성 
        filea.fRead();
        filea.sPlite();

        //예외 처리문 시작 
        try {
            loginfo = filea.returnLoginDataInfo();// sfr100 배열 값들을 그대로 넘겨받는거임 객체복사 아이디 패스워드를 그대로 가져옴 
            for(int k = 0 ; k < loginfo.size(); k ++){
            System.out.println(loginfo.get(k));
            }

        } catch (IOException a) {
            //로그인 이벤트 발생 입출력 오류 발생시 오류를 기록하는 로그기록장치 
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, a);
            // 심각한 오류 발생시 로그로 정보 기록 해당 클래스 이름과 같이 
        }
        String id;
        String pw;

        id = F_ID.getText();
        pw = F_PW.getText();

        alla = false; // 초기 불리언 타임 초기화  로그인 성공여부 판별 

        for (int first = 0; first < loginfo.size(); first++) {
            if (loginfo.get(first).getId().equals(id) && loginfo.get(first).getPs().equals(pw)) {
                if (first == 0) { // 어드민 순서는 무조건 첫번째로 오기때문 
                    JOptionPane.showMessageDialog(null, "관리자님 로그인 성공");

                    try {
                        filea.fWrite(id);

                    } catch (IOException ea) {
                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ea); // 로그인 과정중 파일 입출력 오류 발생기록 
                    }

                    MainMenu nextclass = new MainMenu(); // 메인메뉴 창 호출 
                    nextclass.setVisible(true); //메인 메뉴 컴포넌트 표시 
                    dispose(); // 현재 프레임 종료 +
                    alla = true; // 로그인 성공함 
                    logintype = 0; // 관리자로 로그인했음을 알림 
                    break; // 현재 코드 끝 님

                } else { //0 번째 들어간 값이아닌 나머지 경우 전부다 스테프로 인식 처리 
                    JOptionPane.showMessageDialog(null, "직원(staff님) 로그인 성공! ");

                    try {
                        filea.fWrite(id);// 로그인 로그 기록 
                    } catch (IOException ea) {//파일 읽다가 예외 경우 발생시 처리구문 
                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ea);
                    }
                    MainMenu nextclass = new MainMenu(); // 메인메뉴 창 호출 
                    nextclass.setVisible(true); //메인 메뉴 컴포넌트 표시 
                    dispose(); // 현재 프레임 종료 +
                    alla = true; // 로그인 성공함 
                    logintype = 1; // 직원으로 로그인했음을 알림 
                    break; // 현재 코드 끝 
                }

            }

        }

        if (alla == false) {
            if (id.length() == 0 && pw.length() == 0) {
                JOptionPane.showMessageDialog(null, "ID, PW를 입력하여 주십시오 .", "로그인 실패", JOptionPane.WARNING_MESSAGE);
            } else if (id.length() == 0) {
                JOptionPane.showMessageDialog(null, "ID를 입력하여 주십시오 .", "로그인 실패", JOptionPane.WARNING_MESSAGE);
            } else if (pw.length() == 0) {
                JOptionPane.showMessageDialog(null, "PW를 입력하여 주십시오 .", "로그인 실패", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "ID, PW를 확인해주세요 .", "로그인 실패", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_Login_BUTTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //이전 개발환경 선택 관련 옵션 이동 소스 
        OssystemSelect choose = new OssystemSelect();
        choose.setVisible(true); //메인 메뉴 컴포넌트 표시 
        dispose(); // 현재 프레임 종료 +
    }//GEN-LAST:event_jButton1ActionPerformed
    // 로그인 처리부 함수 끝 
    public int getLogintype() {
        return logintype;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        // 기본인터페이스가 마음에 안들어서 nimbus형 인터페이스로 변환 
        try { // 경로못찾을 경우대비 예외 처리문 사용 시스템 환경에 따라 ui 인터페이스 조정하는 옵션 
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                // 현재 사용가능한 테마를 확인후 사용가능한 테마를 리턴형을 확인 할때까지 반복 개선된 for문 
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName()); // 테마를 찾았으면 해당 태마로 설정 하는구문 
                }
            }
        } /* 자동 생성이긴한데 만약에 클래스이름을 못가져왔을경우 발생하는걸 자동으로 예외 처리를 하고 위험 경고 로그를 자동으로 기록시킴*/ catch (InstantiationException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() { // 실행시켰을때 창을 자동으로 키게하라는 기본으로 만들어져있는거임 
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField F_ID;
    private javax.swing.JPasswordField F_PW;
    private javax.swing.JButton Login_BUTT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
