/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dong.hotel.management;

import dong.hotel.file.CreateStaffId;
import dong.hotel.file.PeakSeasonPayInfoSave;
import dong.hotel.file.PeakSeasonPayProcess;
import dong.hotel.file.SFR100Process;
import dong.hotel.reservation.PeakSeasonChargeInfo;
import java.awt.List;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author heehe
 */
public class EtcEdit extends javax.swing.JFrame {
 private ArrayList<PeakSeasonChargeInfo> cinfo = new ArrayList<>();
    /**
     * Creates new form Report
     */
    public EtcEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffInfo = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        idFiled = new javax.swing.JTextField();
        psFiled = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        IdFiled = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        PsFiled = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        roomInfo = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        roomnum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        personnum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pay = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        changereason = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        room1 = new javax.swing.JTextField();
        person1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pay1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        roomnum3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        Room_BUTT = new javax.swing.JButton();
        staff_BUTT = new javax.swing.JButton();
        Back_BUTT = new javax.swing.JButton();

        staffInfo.setMinimumSize(new java.awt.Dimension(280, 280));

        jLabel9.setText("아이디");

        jLabel10.setText("새로운 비밀번호");

        jButton7.setText("변경");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel11.setText("*아이디는 변경 불가능합니다.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(psFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("변경", jPanel2);

        jLabel12.setText("아이디");

        jLabel13.setText("비밀번호");

        jLabel14.setText("*관리자는 삭제 불가능합니다.");

        jButton8.setText("삭제");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdFiled, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PsFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(IdFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(PsFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("삭제", jPanel1);

        javax.swing.GroupLayout staffInfoLayout = new javax.swing.GroupLayout(staffInfo.getContentPane());
        staffInfo.getContentPane().setLayout(staffInfoLayout);
        staffInfoLayout.setHorizontalGroup(
            staffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        staffInfoLayout.setVerticalGroup(
            staffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("PW변경");

        roomInfo.setMinimumSize(new java.awt.Dimension(400, 350));

        jLabel1.setText("호실");

        jLabel2.setText("인원");

        jLabel3.setText("요금");

        jButton4.setText("변경하기");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setText("요금변경이유");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(personnum, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(roomnum, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changereason)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 66, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(roomnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(personnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changereason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("변경", jPanel3);

        jLabel4.setText("호실");

        jLabel5.setText("인원");

        jLabel6.setText("요금");

        jButton5.setText("추가하기");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pay1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(person1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(room1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(room1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(person1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(40, 40, 40))
        );

        jTabbedPane2.addTab("추가", jPanel4);

        jLabel7.setText("호실");

        jButton6.setText("삭제하기");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(roomnum3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(roomnum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jButton6)
                .addGap(85, 85, 85))
        );

        jTabbedPane2.addTab("삭제", jPanel5);

        javax.swing.GroupLayout roomInfoLayout = new javax.swing.GroupLayout(roomInfo.getContentPane());
        roomInfo.getContentPane().setLayout(roomInfoLayout);
        roomInfoLayout.setHorizontalGroup(
            roomInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        roomInfoLayout.setVerticalGroup(
            roomInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomInfoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Room_BUTT.setText("객실 관리");
        Room_BUTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_BUTTActionPerformed(evt);
            }
        });

        staff_BUTT.setText("사용자 정보 관리");
        staff_BUTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_BUTTActionPerformed(evt);
            }
        });

        Back_BUTT.setText("이전");
        Back_BUTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BUTTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Room_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staff_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(Room_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(staff_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(Back_BUTT)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Room_BUTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_BUTTActionPerformed
        roomInfo.setVisible(true);
    }//GEN-LAST:event_Room_BUTTActionPerformed

    private void staff_BUTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_BUTTActionPerformed
        staffInfo.setVisible(true);
    }//GEN-LAST:event_staff_BUTTActionPerformed

    private void Back_BUTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BUTTActionPerformed
        ManagementMainMenu back = new ManagementMainMenu();
        back.setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_BUTTActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        // 여기가 변경 코드 공간 
        try{
         ArrayList<LoginDataInfo> staffinfo = new ArrayList<>();
         
         String changepw =null;
         String Id =null;
         SFR100Process sr = new SFR100Process();
         Id  = idFiled.getText();
        changepw = psFiled.getText();
        // CreateStaffId stass = new CreateStaffId();
            sr.fRead();
            sr.sPlite();
            
          staffinfo = sr.returnLoginDataInfo();
          //System.out.println(staffinfo.size());
          for(int i = 0 ; i< staffinfo.size(); i++){
             // System.out.println(staffinfo.get(i).getPs().equals(changepw));
              if(staffinfo.get(i).getId().equals(Id)){
                  String str = staffinfo.get(i).getId() + " " + staffinfo.get(i).getPs();
                   System.out.println("if조건문 들감 ");
                  if(i==0){ // 관리자인지 직원인지 객체배열 거기따라 들어감 
                      //try{// admin은 새로추가 삭제 불가능 하기때문에 항상 고정위치 
                          sr.AWrite(staffinfo.get(i).getId() + " "+ psFiled.getText());
                           System.out.println("if조건문 들감1 ");
                           JOptionPane.showMessageDialog(null, "관리자 변경완료");
                     // }catch(IOException e){
                      //    e.getStackTrace();
                     // }
                  }else {
                      System.out.println("if조건문 들감2 ");
                     // try{
                       //  BufferedWriter log = new BufferedWriter(new FileWriter("/Users/nifskorea/Desktop/DB/staffID.txt", false));
                         //       log.close();
                          
                      for(int j = 1; j<staffinfo.size(); j++){
                          if(staffinfo.get(j).getId().equals(Id)){
                              System.out.println("if조건문 들감2 ");
                              // str = staffinfo.get(j).getId() + " " + psFiled.getText();
                            // System.out.println(str);
                              sr.Inputvalue(staffinfo.get(j).getId(), psFiled.getText());
                          }else{
                            // str = staffinfo.get(j).getId() + " " + staffinfo.get(j).getPs();
                         // System.out.println(str);
                         //JOptionPane.showMessageDialog(null, "변경할려는 아이디가 일치하지않습니다");
                               sr.Inputvalue(staffinfo.get(j).getId(), staffinfo.get(j).getPs());
                          } //else
                           
                      }//for
                     // } //try
                     // catch(IOException ex){
                     //     ex.getStackTrace();
                    //  }
                  }//else
                   JOptionPane.showMessageDialog(null, "변경 완료");
                    idFiled.setText("");
                    psFiled.setText("");
              }
          }
          
          
        }
        catch(IOException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        // 삭제 
           // 여기가 변경 코드 공간 
        try{
         ArrayList<LoginDataInfo> staffinfo = new ArrayList<>();
         
         String pw =null;
         String Id =null;
         SFR100Process sr = new SFR100Process();
         Id  = IdFiled.getText();
        pw = PsFiled.getText();
        // CreateStaffId stass = new CreateStaffId();
            sr.fRead();
            sr.sPlite();
            
          staffinfo = sr.returnLoginDataInfo();
          //System.out.println(staffinfo.size());
          for(int i = 0 ; i< staffinfo.size(); i++){
             // System.out.println(staffinfo.get(i).getPs().equals(changepw));
              if(staffinfo.get(i).getId().equals(Id)){
                  String str = staffinfo.get(i).getId() + " " + staffinfo.get(i).getPs();
                   System.out.println("if조건문 들감 ");
                  if(i!=0){ // 관리자인지 직원인지 객체배열 거기따라 들어감 
                      //try{// admin은 새로추가 삭제 불가능 하기때문에 항상 고정위치 
                          staffinfo.remove(i);
                           System.out.println("if조건문 들감1 ");
                     // }catch(IOException e){
                      //    e.getStackTrace();
                     // }
                      JOptionPane.showMessageDialog(null, "삭제가 완료되었습니다.");
                  }else  {
                      JOptionPane.showMessageDialog(null, "관리자는 삭제할 수 없습니다.");
                        break;
                  }//else
                  for(int j = 1; j<staffinfo.size(); j++){
                              System.out.println("if조건문 들감2 ");
                               sr.Inputvalue(staffinfo.get(j).getId(), staffinfo.get(j).getPs());
                      }//for
                    IdFiled.setText("");
                   PsFiled.setText("");
              }
          }
          
          
        }
        catch(IOException ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // 객실 요금 변경이유 
       String roomnuma =  roomnum.getText();
        String personnuma = personnum.getText();
       String paya =  pay.getText();
        String changereasona= changereason.getText();
         PeakSeasonPayInfoSave save = new PeakSeasonPayInfoSave();
            PeakSeasonPayProcess chargeinfo = new PeakSeasonPayProcess();
            try{
       chargeinfo.fRead();
       chargeinfo.sPlite();
       cinfo = chargeinfo.returnChargeInfo();
       for (int i = 0; i < cinfo.size(); i++) {
           int roomnume =  Integer.parseInt(roomnuma);
                if ( cinfo.get(i).getRoom()== roomnume) {
                    save.InChargeInfo(i, roomnuma, cinfo.get(i).getNumpeople(),
                           paya, cinfo.get(i).getExtractcharge(),
                            cinfo.get(i).getNumpeople(),changereasona);// 정보 넣기

                    JOptionPane.showMessageDialog(null, "변경 완료");
                    pay.setText("");
                }
            }
            }
            catch(IOException ex){
                ex.getStackTrace();
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
        String roomnuma =  room1.getText();
        String personnuma = person1.getText();
       String paya =  pay1.getText();
       int temp =0;
       int count = 0;
         PeakSeasonPayInfoSave save = new PeakSeasonPayInfoSave();
            PeakSeasonPayProcess chargeinfo = new PeakSeasonPayProcess();
            
            chargeinfo.fRead();
            chargeinfo.sPlite();
           cinfo = chargeinfo.returnChargeInfo();
            if(paya.isEmpty() || roomnuma.isEmpty() ||personnuma.isEmpty()){
                 JOptionPane.showMessageDialog(null, "정확히 입력해주세요.");
            }else {
                temp = Integer.parseInt(roomnuma);
                for (int i = 0; i < cinfo.size(); i++) {
                    if (cinfo.get(i).getRoom() == temp) {
                        JOptionPane.showMessageDialog(null, "이미 있는 호실입니다.");
                       count = 1;
                    }
                }
                if (count == 0) {
                   
                    save.fWritea(1, roomnuma, personnuma,
                           paya, "10000",
                            "15","이유없음");// 정보 넣기
                    JOptionPane.showMessageDialog(null, "추가했습니다!");
                    pay.setText("");
                }
                count = 0;
            }
        }
        catch(IOException ex ){
            ex.getStackTrace();
        }
            
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //호실 삭제 
        try{
        String roomnuma =  roomnum3.getText();
       int temp =0;
       int count = 0;
         PeakSeasonPayInfoSave save = new PeakSeasonPayInfoSave();
            PeakSeasonPayProcess chargeinfo = new PeakSeasonPayProcess();
            
            chargeinfo.fRead();
            chargeinfo.sPlite();
           cinfo = chargeinfo.returnChargeInfo();
            
                temp = Integer.parseInt(roomnuma);
             //   System.out.println (cinfo.size());
                for (int i = 0; i < cinfo.size(); i++) {
                    //System.out.println(cinfo.get(i).getRoom());
                    if (cinfo.get(i).getRoom() == temp) {
                        cinfo.remove(i);
                        System.out.println("조건문통과1 ");
                         int temp2 =   cinfo.get(i).getRoom();
                        
                           String temp3  = Integer.toString(temp2);
                            System.out.println(i+temp3+cinfo.get(i).getNumpeople()+cinfo.get(i).getRoomcharge()+cinfo.get(i).getExtractcharge()+
                    cinfo.get(i).getMaxpele()+cinfo.get(i).getAddreason());
                           save.fWritetwo(i,temp3,cinfo.get(i).getNumpeople(),cinfo.get(i).getRoomcharge(),cinfo.get(i).getExtractcharge(),
                   cinfo.get(i).getMaxpele(),cinfo.get(i).getAddreason());// 정보 넣기
                        JOptionPane.showMessageDialog(null, "호실삭제");
                      //  break;
                    }
                    else {
                        int temp2 =   cinfo.get(i).getRoom();
                           String temp3  = Integer.toString(temp2);
                       System.out.println(i+temp3+cinfo.get(i).getNumpeople()+cinfo.get(i).getRoomcharge()+cinfo.get(i).getExtractcharge()+
                    cinfo.get(i).getMaxpele()+cinfo.get(i).getAddreason());
                       save.fWritetwo(i,temp3,cinfo.get(i).getNumpeople(),cinfo.get(i).getRoomcharge(),cinfo.get(i).getExtractcharge(),
                    cinfo.get(i).getMaxpele(),cinfo.get(i).getAddreason());// 정보 넣기
                       
                    }
                   //JOptionPane.showMessageDialog(null, "호실을 잘못입력하셨습니다. ");
        }
               
        }
        catch(IOException ex ){
            ex.getStackTrace();
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EtcEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EtcEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EtcEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtcEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EtcEdit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EtcEdit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EtcEdit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtcEdit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               new EtcEdit().setVisible(true);
            }
        });
       
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_BUTT;
    private javax.swing.JTextField IdFiled;
    private javax.swing.JTextField PsFiled;
    private javax.swing.JButton Room_BUTT;
    private javax.swing.JTextField changereason;
    private javax.swing.JTextField idFiled;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField pay;
    private javax.swing.JTextField pay1;
    private javax.swing.JTextField person1;
    private javax.swing.JTextField personnum;
    private javax.swing.JTextField psFiled;
    private javax.swing.JTextField room1;
    private javax.swing.JDialog roomInfo;
    private javax.swing.JTextField roomnum;
    private javax.swing.JTextField roomnum3;
    private javax.swing.JDialog staffInfo;
    private javax.swing.JButton staff_BUTT;
    // End of variables declaration//GEN-END:variables
}
