/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dong.hotel.mainmenu;

import dong.hotel.reservation.ReservationMenu;
import dong.hotel.search.Search;
import dong.hotel.check.CheckIN;
import dong.hotel.check.CheckOut;
import dong.hotel.file.CustomerInforSave;
import dong.hotel.file.Sfr200Process;
import dong.hotel.management.ManagementMainMenu;
import dong.hotel.login.Login;
import dong.hotel.reservation.CustomerInfor;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
// 테스팅

/**
 *
 * @author heehe
 */
public class MainMenu extends javax.swing.JFrame {

    private ArrayList<CustomerInfor> customerinfo = new ArrayList<>();

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SEARCH_BUTT = new javax.swing.JButton();
        RESERVATION_BUTT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CHECKIN_BUTT = new javax.swing.JButton();
        CHECKOUT_BUTT = new javax.swing.JButton();
        EDIT_BUTT = new javax.swing.JButton();
        LOGOUT_BUTT = new javax.swing.JButton();
        updateB = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("굴림", 1, 25)); // NOI18N
        jLabel1.setText("호텔 관리 시스템");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SEARCH_BUTT.setText("예약 조회");
        SEARCH_BUTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_BUTTActionPerformed(evt);
            }
        });

        RESERVATION_BUTT.setText("예약");
        RESERVATION_BUTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESERVATION_BUTTActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("굴림", 1, 25)); // NOI18N
        jLabel2.setText("호텔 관리 시스템");

        CHECKIN_BUTT.setText("체크인");
        CHECKIN_BUTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECKIN_BUTTActionPerformed(evt);
            }
        });

        CHECKOUT_BUTT.setText("체크아웃");
        CHECKOUT_BUTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECKOUT_BUTTActionPerformed(evt);
            }
        });

        EDIT_BUTT.setText("관리 및 보고서");
        EDIT_BUTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDIT_BUTTActionPerformed(evt);
            }
        });

        LOGOUT_BUTT.setText("로그아웃");
        LOGOUT_BUTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUT_BUTTActionPerformed(evt);
            }
        });

        updateB.setText("🔄새로고침");
        updateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CHECKIN_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CHECKOUT_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RESERVATION_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SEARCH_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EDIT_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LOGOUT_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(updateB)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SEARCH_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RESERVATION_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHECKOUT_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CHECKIN_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LOGOUT_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EDIT_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateB)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RESERVATION_BUTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESERVATION_BUTTActionPerformed
        ReservationMenu next = new ReservationMenu();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_RESERVATION_BUTTActionPerformed

    private void SEARCH_BUTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_BUTTActionPerformed
        Search next = new Search();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_SEARCH_BUTTActionPerformed

    private void CHECKIN_BUTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECKIN_BUTTActionPerformed
        CheckIN next = new CheckIN();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_CHECKIN_BUTTActionPerformed

    private void CHECKOUT_BUTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECKOUT_BUTTActionPerformed
        CheckOut next = new CheckOut();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_CHECKOUT_BUTTActionPerformed

    private void EDIT_BUTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDIT_BUTTActionPerformed
        // TODO add your handling code here:
        //관리자만 접근가능하도록!
        Login logas = new Login();
        if (logas.getLogintype() == 0) { // 관리자 식별 
            ManagementMainMenu next = new ManagementMainMenu();
            next.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "관리자가 아닌 스태프 권환이므로 접근권환이 없습니다. 관리자에게 문의하십시오. ");
        }

    }//GEN-LAST:event_EDIT_BUTTActionPerformed

    private void LOGOUT_BUTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUT_BUTTActionPerformed
        // TODO add your handling code here:
        Login next = new Login();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_LOGOUT_BUTTActionPerformed

    private void updateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBActionPerformed
        String hour = new SimpleDateFormat("HH").format(System.currentTimeMillis());
        int h = Integer.parseInt(hour);
        if (h > 17) {// 6시 이후에
            try {
                Sfr200Process cF = new Sfr200Process();
                cF.fRead();
                cF.sPlite();
                customerinfo = cF.returnGuestInfo();
                //시스템 날짜
                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                String date = df.format(System.currentTimeMillis());
                Date systemDate = df.parse(date);
                int d=0;
                int u=0;
                for (int i = 0; i < customerinfo.size(); i++) {
                    //예약일 포맷
                    String checkIn = String.format("%s-%s-%s", customerinfo.get(i).getcInYear(), customerinfo.get(i).getcInMonth(), customerinfo.get(i).getcInDay());
                    Date inDate = df.parse(checkIn);
                    if (systemDate.compareTo(inDate) == 0) {//체크인날짜라면
                        if (customerinfo.get(i).getGuarantee().equals("예약고객")) {
                            //예약자삭제
                            CustomerInforSave updateGuest = new CustomerInforSave();
                            updateGuest.updateGuest(customerinfo.get(i).getChechkNum(), " ", " "," "," ", " "," "," ", " ", " ", " "," ", " ", " "," "," ", "예약취소");
                            d++;
                        } else if (customerinfo.get(i).getGuarantee().equals("보증고객")) {
                            //예약자정보수정
                            CustomerInforSave updateGuest = new CustomerInforSave();
                            updateGuest.updateGuest(customerinfo.get(i).getChechkNum(), customerinfo.get(i).getName(), customerinfo.get(i).getRoomNum(),
                                    customerinfo.get(i).getCustomerNum(), customerinfo.get(i).getPhoneNum(), customerinfo.get(i).getcInYear(), customerinfo.get(i).getcInMonth(),
                                    customerinfo.get(i).getcInDay(), customerinfo.get(i).getcOutYear(), customerinfo.get(i).getcOutMonth(), customerinfo.get(i).getcOutDay(),
                                    customerinfo.get(i).getRoomPrice(), customerinfo.get(i).getCard(), customerinfo.get(i).getCardNum(), customerinfo.get(i).getEndMonth(),
                                    customerinfo.get(i).getEndYear(), "필수결제");
                            u++;
                        }
                    }
                } 
                if(d>0||u>0){
                    JOptionPane.showMessageDialog(null, "예약 고객 정보 업데이트 완료");
                }else if(d==0&&u==0){
                    JOptionPane.showMessageDialog(null, "업데이트된 정보가 없습니다.");                    
                }
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "18시 이후에 새로고침이 가능합니다.");
        }
    }//GEN-LAST:event_updateBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CHECKIN_BUTT;
    private javax.swing.JButton CHECKOUT_BUTT;
    private javax.swing.JButton EDIT_BUTT;
    private javax.swing.JButton LOGOUT_BUTT;
    private javax.swing.JButton RESERVATION_BUTT;
    private javax.swing.JButton SEARCH_BUTT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton updateB;
    // End of variables declaration//GEN-END:variables
}
